[book]
authors = ["burrrata"]
multilingual = false
src = "src"
title = "Crypto Wars"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true

[dependancies]
rust-crypto = "0.2.36"
